### ISSUE TITLE
Term object id convention

### ISSUE THREAD

**Issue by jjrom** [stac-extensions/themes#2]
Hi Emmanuel - this proposal is a nice initiative :) As you mentioned resto, I’ve some concern with the constraint set on the id for the Term Object. Your proposed format is <system_id>::<id>. This raise two issues on resto. First the separator is a « :: » while in resto it’s a single « : ». Secondly, the system_id is a constraint value from a list (currently geonames and wiki) while in resto this value is opened to allow any prefix. Additionnaly, I would not restrict the id to one separator and allow multiple separator (for instance geonames::935877::Piton De La Fournaise) - for instance to avoid a lookup on geonames in this case

**Comment by emmanuelmathot** [comment]
Hello Jérome, Thank you for the comment.
The idea behind the conventional identifier is to make sure that a STAC API search query performs a similar behaviour through several implementation.

For instance
`filter=subjects:terms.id = geonames:935877`

without ambiguity from the name representation (e.g language used)

the field `name` allows more free search such as

`filter=subjects:terms.name LIKE Piton%`

**Comment by m-mohr** [comment]
We follow Records now, which doesn't imply any id conventions so I think we are good?!

**Comment by ycespb** [comment]
How would a (STAC) queryable and corresponding  filter expression now look like for the themes encoding proposed in this extension ?   In the [API Records specification](https://docs.ogc.org/DRAFTS/20-004r1.html), the encoding of concepts is an array of strings instead of an array of objects:

https://example.org/collections/myCatalog/items?scheme=https%3A%2F%2Fgeo.woudc.org%2Fcodelists.xml%23WOUDC_InstrumentCode&concept=spectral,hoelper

The above API Records example assumes /queryables like "scheme" and "concept" with concept being a string.

Does the STAC extension then expects that /queryables contain "scheme" and "concepts.id" or "concepts.title" or "properties.themes.concepts.id" and  "properties.themes.concepts.tiitle" ?

**Comment by m-mohr** [comment]
The fields are exactly the same in Records and STAC, they just pre-defined a query parameter for search afaik. You can define the same search parameter as a queryable in STAC, using a array of strings schema and then handle the input accordingly in your server-side implementation.
